### ISSUE TITLE
Unable to login or see progress

### ISSUE THREAD

**Issue by ajtruex** [Hacktoberfest-2018/Hello-world#3396]
When navigating to [https://hacktoberfest.digitalocean.com/](https://hacktoberfest.digitalocean.com/) I am only given the option to register. 

I'd like to sign in and check my progress but that does not seem to be an option.

**Comment by JamesKingdom** [comment]
@ajtruex 
I know this is the wrong repo but did you solve this?
Just click "Register now", and log in with github.
It'll skip the register step and sign you in.
Now if you go back to the hacktoberfest home page, you should see "check your progress".

Or just use this url [https://hacktoberfest.digitalocean.com/stats/ajtruex](https://hacktoberfest.digitalocean.com/stats/ajtruex)
