### ISSUE TITLE
Shameless Plug

### ISSUE THREAD

**Issue by jrg94** [Hacktoberfest-2018/Hello-world#483]
Hey! These kind of repos only pop up once a year, and they're very rarely maintained. I have a repo that accomplishes exactly the same thing as this repo, but it's built for the long haul. In fact, we even write articles explaining our code snippets. 

It's just as easy to contribute to our repo, so consider sharing your code snippets with us: https://github.com/TheRenegadeCoder/sample-programs

**Comment by Aniket965** [comment]
hey we believe in diversity

**Comment by jrg94** [comment]
Agreed! We use the Contributor Covenant Code of Conduct over at Sample Programs. But, how does that apply here?

**Comment by Aniket965** [comment]
this is not about sample programs we help newcomers to get started only! they can learn to contribute in more flexible repo and learn the way to more maintained repo

**Comment by jrg94** [comment]
Agreed! Then, our repos have a lot in common.
